export const usersTypes = {
  GET_USERS: "GET_USERS",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER"
}

export const clientsTypes = {
  GET_CLIENTS: "GET_CLIENTS",
  ADD_CLIENT: "ADD_CLIENT",
  UPDATE_CLIENT: "UPDATE_CLIENT",
  REMOVE_SELECTED_CLIENT: "REMOVE_SELECTED_CLIENT"
}

export const servicesTypes = {
  GET_SERVICES: "GET_SERVICES",
  ADD_SERVICE: "ADD_SERVICE",
  UPDATE_SERVICE: "UPDATE_SERVICE",
  REMOVE_SELECTED_SERVICE: "REMOVE_SELECTED_SERVICE"
}

export const barbersTypes = {
  GET_BARBERS: "GET_BARBERS",
  ADD_BARBER: "ADD_BARBER",
  UPDATE_BARBER: "UPDATE_BARBER",
  REMOVE_SELECTED_BERBER: "REMOVE_SELECTED_BERBER"
}

export const turnsTypes = {
  GET_TURNS: "GET_TURNS",
  ADD_TURN: "ADD_TURN",
  UPDATE_TURN: "UPDATE_TURN",
  REMOVE_SELECTED_TURN: "REMOVE_SELECTED_TURN"
}

export const hoursTypes = {
  GET_HOURS: "GET_HOURS",
  UPDATE_HOURS: "UPDATE_HOURS"
}

export const daysTypes = {
  GET_DAYS: "GET_DAYS",
  UPDATE_DAYS: "UPDATE_DAYS"
}
